In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
np.average(x)

3.0

In [7]:
(a, b) = np.array((3,2))

In [6]:
a

3

In [18]:
def trial(x,y):
    print('x: ', np.shape(x), ' y: ', np.shape(y))
    print(x + y)

In [8]:
x = np.reshape(np.arange(24), (2,3,4))

In [9]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
y1 = np.arange(1)
y2 = np.arange(2)
y3 = np.arange(3)
y4 = np.arange(4)

In [24]:
z34 = np.outer(y3, y4)
print(np.shape(z34))
print(z34)

(3, 4)
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [23]:
trial(x,z34)

x:  (2, 3, 4)  y:  (3, 4)
[[[ 0  1  2  3]
  [ 4  6  8 10]
  [ 8 11 14 17]]

 [[12 13 14 15]
  [16 18 20 22]
  [20 23 26 29]]]
