In [1]:
L = ["Oh", "Say", "does", "that", "star",
     "spangled", "banner", "yet", "wave"]

In [7]:
for x in L:
    if len(x) > 3:
        print x

does
that
star
spangled
banner
wave


In [28]:
s = 'my name is jinsoo !'
sentence = []
sentence = s.split()

In [29]:
sentence

['my', 'name', 'is', 'jinsoo', '!']

In [30]:
sentence[0]

'my'

In [40]:
s2 = sentence[0]
for x in sentence:
    s2 += x + " "
s2

'mymy name is jinsoo '

In [34]:
sentence.pop()
sentence

['my', 'name', 'is', 'jinsoo']

In [35]:
sentence.append('!')

In [36]:
sentence

['my', 'name', 'is', 'jinsoo', '!']

In [37]:
exc = sentence.pop()
exc

'!'

In [1]:
import numpy as np

In [2]:
x = np.arange(10)**2
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [3]:
x[5:8]

array([25, 36, 49])

In [7]:
x[[1,-1]]

array([ 1, 81])

In [8]:
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
y = x.copy()
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
y[5] = 1000
y

array([   0,    1,    4,    9,   16, 1000,   36,   49,   64,   81])

In [11]:
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
z = np.ones((2,3))
z

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
z.shape

(2L, 3L)

In [15]:
print z.shape

(2L, 3L)


In [16]:
print len(z)

2


In [21]:
print np.size(z)
print z.shape[1]

6
3


In [18]:
print len(L)

NameError: name 'L' is not defined

In [19]:
L = ["Oh", "Say", "does", "that", "star",
     "spangled", "banner", "yet", "wave"]

In [20]:
print len(L)

9


In [22]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
len(x)

3

In [24]:
x[:,0]

array([0, 4, 8])

In [25]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

indexing arrays# 

In [26]:
x = np.arange(10)**2
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
inds = [0,-1]
x[inds]

array([ 0, 81])

In [28]:
inds = [1,3,1,3,1,3,1,3]
x[inds]

array([1, 9, 1, 9, 1, 9, 1, 9])

boolean arrays and indexing with them## 

In [29]:
x > 20

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [30]:
x[x > 20]

array([25, 36, 49, 64, 81])

In [31]:
small = x < 10
big = x > 70
print x[small]
print x[big]

[0 1 4 9]
[81]


In [32]:
x[small | big] #combining multiple conditions

array([ 0,  1,  4,  9, 81])

In [33]:
x = np.arange(10) - 5
y = np.arange(10)*2 - 10
print x
print y

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-10  -8  -6  -4  -2   0   2   4   6   8]


In [34]:
x > y

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [35]:
x[x>y]

array([-5, -4, -3, -2, -1])

# random number gen### 

In [37]:
x = np.random.random()
x

0.8626165735881123

In [38]:
x = np.ones((2,3))*np.random.random()
x

array([[ 0.8912547,  0.8912547,  0.8912547],
       [ 0.8912547,  0.8912547,  0.8912547]])

In [41]:
y = np.random.random(10)

In [42]:
y

array([ 0.64335025,  0.84049074,  0.25444691,  0.60423701,  0.72683493,
        0.70781312,  0.69744917,  0.72984099,  0.02390339,  0.76806867])

In [43]:
y(0)

TypeError: 'numpy.ndarray' object is not callable

In [44]:
y[0]

0.64335024505200578