In [1]:
import numpy as np

from rotation import rotation, circle

In [2]:
rotation(30)

array([[ 0.8660254,  0.5      ],
       [-0.5      ,  0.8660254]])

In [13]:
circ = circle()
circ.round(3)

array([[ 1.   ,  0.   ],
       [ 0.94 ,  0.342],
       [ 0.766,  0.643],
       [ 0.5  ,  0.866],
       [ 0.174,  0.985],
       [-0.174,  0.985],
       [-0.5  ,  0.866],
       [-0.766,  0.643],
       [-0.94 ,  0.342],
       [-1.   ,  0.   ],
       [-0.94 , -0.342],
       [-0.766, -0.643],
       [-0.5  , -0.866],
       [-0.174, -0.985],
       [ 0.174, -0.985],
       [ 0.5  , -0.866],
       [ 0.766, -0.643],
       [ 0.94 , -0.342]])

In [14]:
rotated_circ = circ.dot(rotation(30))*2
rotated_circ.round(3)

array([[ 1.732,  1.   ],
       [ 1.286,  1.532],
       [ 0.684,  1.879],
       [ 0.   ,  2.   ],
       [-0.684,  1.879],
       [-1.286,  1.532],
       [-1.732,  1.   ],
       [-1.97 ,  0.347],
       [-1.97 , -0.347],
       [-1.732, -1.   ],
       [-1.286, -1.532],
       [-0.684, -1.879],
       [-0.   , -2.   ],
       [ 0.684, -1.879],
       [ 1.286, -1.532],
       [ 1.732, -1.   ],
       [ 1.97 , -0.347],
       [ 1.97 ,  0.347]])